### ISSUE TITLE
Issues with importing bitshuffle's h5 module since PR #81

### ISSUE THREAD

**Issue by anjakefala** [kiyo-masui/bitshuffle#105]
Since https://github.com/kiyo-masui/bitshuffle/commit/6899f5db159469e92e7b3c776d2087345e4d5b77 I have had issues with running [caput](https://github.com/radiocosmology/caput) and [dias](https://github.com/chime-experiment/dias) builds on github actions.

`pip install --no-binary=h5py h5py` results in a segmentation fault. If I changed that to `pip install h5py`, there are no Segmentation Fault, but I still have issues with loading modules that import `h5`. Regrettably, I opted into pinning to an older `bitshuffle` version in the meantime instead of putting more time into this.

This is limited information, but I am available to help with reproducing. In particular, any new PR with `caput` and `dias`, that installs `bitshuffle` from the `master` branch will reproduce the issue.

**Comment by james-s-willis** [comment]
Hey @anjakefala, can you link the github actions build that reproduces it?

**Comment by anjakefala** [comment]
Reproduction available here: https://github.com/chime-experiment/dias/pull/199

This PR is available for you to play with, there are not major commits on it.

**Comment by anjakefala** [comment]
Thanks @james-s-willis for addressing this! :tada:
