### ISSUE TITLE
when to release AVX-512 version?

### ISSUE THREAD

**Issue by wanweiqiangintel** [kiyo-masui/bitshuffle#128]
The AVX-512 version has been merged into the master branch for several months, so can we expect to release it.

**Comment by wanweiqiangintel** [comment]
@jrs65 and @kiyo-masui Could you help check if it is OK for releasing the latest version of this repo?

**Comment by jrs65** [comment]
Hi @wanweiqiangintel

Yes you are right we should try and cut another release. I'd like to figure out the issues building wheels with broad microarchitecture support first (#121), but when that's figured out I think we should do a release.

**Comment by jrs65** [comment]
I just released [v0.5.0](https://github.com/kiyo-masui/bitshuffle/releases/tag/0.5.0) with AVX512 support in there. It won't be built into the binary wheels as I'd need to do some large refactoring to have it dispatch to different methods at run time, so to get AVX512 support people will need to build bitshuffle from source.
