### ISSUE TITLE
Single byte dtypes

### ISSUE THREAD

**Issue by alimanfoo** [kiyo-masui/bitshuffle#22]
Apologies for the naive question, I have large arrays with int8 dtype but where most values are 0, 1 or 2. Can bitshuffle improve compression of arrays with a single-byte dtype?

**Comment by kiyo-masui** [comment]
Yup.  Expect that data to compress to something like 25% or better.

**Comment by alimanfoo** [comment]
Thanks, I'm using blosc and it turns out there was a bug in the version I was using where bitshuffle wasn't applied to single byte dtypes. Using a more recent version of blosc with bitshuffle I see a significant improvement in compression with some real-world data, benchmarks in [this notebook](http://nbviewer.ipython.org/gist/alimanfoo/e93a532eb6bde311ea39/genotype_bitshuffle.ipynb) if you're interested.

**Comment by kiyo-masui** [comment]
Thanks for passing this along. Happy to see bitshuffle stacks up well.
