### ISSUE TITLE
Select AVX, SSE, or non-optimized code at runtime

### ISSUE THREAD

**Issue by toddlipcon** [kiyo-masui/bitshuffle#41]
For cases where users are not compiling bitshuffle themself, but rather using it in a shipped product, it's difficult to know ahead of time that the target architecture will support these instruction sets.

To get optimal runtime performance, bitshuffle should auto-detect the runtime architecture and pick the appropriate algorithm, either by an indirect branch, or by using gcc's 'ifunc' feature.

**Comment by kiyo-masui** [comment]
This seems like an obviously good idea. However, I have no experience shipping binaries nor do I have any need to at this time. As it would take me some time to figure out what the best way to do this is, I'm not going to take it on at this time. As always, pull requests are welcome.

**Comment by toddlipcon** [comment]
FWIW I did this with a hack on the consuming system rather than changing bitshuffle. https://github.com/apache/kudu/commit/f10ab4a1d7ac0735890dcab6685a9fba7edac74e in case anyone's interested. So, I probably won't take the time to do it in the upstream lib.
