### ISSUE TITLE
 About LZ4 and AVX, bitshuffle

### ISSUE THREAD

**Issue by JaeSeungHan** [kiyo-masui/bitshuffle#69]
Hi, I am carrying out research on the block data transmission using lz4 compression, and in the process of that, I get to know bit shuffle. If I use bit shuffle and compress lz4, is the compression speed faster? And in bit shuffle, I saw that SSE and AVX instructions are included. Do you use AVX instructions to speed up bit shuffling?  Thanks for read it.

**Comment by kiyo-masui** [comment]
Bitshuffle+LZ4 is not faster than LZ4: there is extra computation for the bitshuffle and this slows things down, typically by a factor of a few.

Bitshuffle itself is optimized using AVX and SSE as available, making it much faster.
