### ISSUE TITLE
`pip install bitshuffle` fails ... on python3.7

### ISSUE THREAD

**Issue by kif** [kiyo-masui/bitshuffle#76]
This has to do with the cythonized files shipped while some internal *struct* from Python changed in recent version, preventing the C-file to build.

Setting a build dependency on Cython and using it to transcode the **pyx** files to **c** at the build-time is a safe option.

Do you think it is possible to provide a manylinux wheel for bitshuffle ?

**Comment by Czaki** [comment]
same here

**Comment by kif** [comment]
The **hdf5plugin** projects is now available and provides this plugin + a couple of other. Just `pip install hdf5plugin`

**Comment by Czaki** [comment]
patching other code which as use needs more wort than install with `git+...`

**Comment by dirkboye** [comment]
bump! I'd really like to use `pip install bitshuffle` on python 3.7 as I don't need the hdf5plugin in python but only the bare compress/decompress methods

**Comment by kif** [comment]
The recipe is quite simple but it requires a new release of bitshuffle ... not in my hands

**Comment by Czaki** [comment]
Why?

**Comment by Czaki** [comment]
If I create bitshulfe wheels for macos and linux (with CI) it is option for you to upload it?

**Comment by kif** [comment]
I can also create such wheels ... but I don't own this repo, neither can I upload bitshuffle to PyPI.
On the other hand, hdf5plugin (for which I can act) does not expose the python API of those compression methods, would it make sense to expose them ?
The alternative is an unfriendly fork, but that's not the best way to develop open source software ...

**Comment by dirkboye** [comment]
if you would expose the python api (compress_lz4/decompress_lz4 from extension ext) that would help quite a lot!

**Comment by Czaki** [comment]
@kif Sorry for confusing you with @kiyo-masui

**Comment by kiyo-masui** [comment]
Sorry for neglecting this folks.

The problem with providing wheels is that bitshuffle needs to be linked against the same hdf5 as h5py, so both need to be built from source on every machine.

Is there a way to fix this at the cython dependency level? I could remove the xython generated files from the repo (I'm not sure what best practice is for distributing cython stuff). Is there another way of fixing it that I'm not thinking of? Sorry, I'm not super experienced at packaging.

**Comment by Czaki** [comment]
@kiyo-masui  You force to use cython during bitshuffle build so there is no need to have `*.c` files in repository or sdist. 

Wheel allow to embed shared libraries. For my projects I use cibuildwheel which allow simply build wheel using continious integration. I can help with this.

**Comment by kiyo-masui** [comment]
Yeah okay, I'll scrub out the cythonized files.

If you install both bitshuffle and h5py from wheels (and h5py is statically linked), I don't see how you can ensure they are linked against the same version of the hdf5 libraries. At the very least I would have to upload new wheels every time h5py did (which is a pain) and even then users who don't install h5py and bitshuffle at the same time will run into problems. No?

**Comment by Czaki** [comment]
I check h5py wheels andt h5py is dynamically linked to libraries. And this library is embedded in the wheel.
![Zrzut ekranu z 2020-03-03 13-59-24](https://user-images.githubusercontent.com/3826210/75778015-56526600-5d57-11ea-9398-4a996dc2de5f.png)

Still information that h5py should be installed from source is somehow on bottom and many users will ignore it.  You use function pointer or something similar that force same library version?

**Comment by kiyo-masui** [comment]
Okay, that's promising... I guess we need to point the the linker to the libraries packaged with h5py. If you can give that a shot that would be great!

**Comment by kif** [comment]
On Tue, 03 Mar 2020 03:43:37 -0800
Kiyoshi Masui <notifications@github.com> wrote:

> The problem with providing wheels is that bitshuffle needs to be linked against the same hdf5 as h5py, so both need to be built from source on every machine.

In hdf5plugin, we have investigated this issue and found a way to link
(at runtime) to the hdf5 library h5py is actually using.

@t20100, do you believe this trick is directly applicable to bitshuffle ?

**Comment by t20100** [comment]
I don't see any reason for the approach used in [hdf5plugin](https://github.com/silx-kit/hdf5plugin) not to work here.

The trick is to avoid linking to libhdf5 by using a small wrapper over libhdf5 (https://github.com/silx-kit/hdf5plugin/blob/master/src/hdf5_dl.c) which provides the API used by the compression plugin but uses `dlopen/dlsym` to load the symbols at runtime.
One can consider this ugly, but I think it is less ugly than being forced to link plugins directly to the core library.

**Comment by dirkboye** [comment]
firendly ping! @kif should i create an issue in silx-kit/hdf5plugin to expose the python api (compress_lz4/decompress_lz4 from extension ext)?

**Comment by t20100** [comment]
It is not the goal of `hdf5plugin` to provide access to the bitshuffle Python API.
`hdf5plugin` is just there to provide an easy way to install HDF5 compression filters and it would not exists if it was simpler to do so.

**Comment by Czaki** [comment]
@t20100 But if You havew solution working in `hdf5plugin` maybe it is possible to You to create PR to this repository with this small file?

**Comment by t20100** [comment]
I can try to propose something.

**Comment by dirkboye** [comment]
@t20100 ok, i understand! (was something @kif proposed in one of his comments)

**Comment by t20100** [comment]
@dirkboye Yes

**Comment by t20100** [comment]
That's what I explained here: https://github.com/kiyo-masui/bitshuffle/issues/76#issuecomment-595661333

**Comment by t20100** [comment]
An alternative could also be to provide `bitshuffle` wheels without the HDF5 filters.

**Comment by dirkboye** [comment]
I like that idea!

**Comment by jrs65** [comment]
I believe this is now fixed.
