### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by FrancescAlted** [kiyo-masui/bitshuffle#9]
I am the author of the Blosc compression library (http://blosc.org), and I have just seen your work on bitshuffle, which I find pretty nice.  I might be interested in including your code in Blosc, but bitshuffling choosing GPL chokes with MIT used in Blosc.

Would you like to change bitshuffling license so that parts of your code could be easily included in other MIT/BSD projects?

Thanks!

**Comment by FrancescAlted** [comment]
It took a while, but a preliminary backport og bitshuffle to c-blosc is here: https://github.com/Blosc/c-blosc/pull/146

Thanks again!

**Comment by kiyo-masui** [comment]
This looks great.  Hopefully your users find it useful.

Kiyo

**Comment by FrancescAlted** [comment]
The port is completed now (with runtime detection for AVX2, so that you can run AVX2-enhanced binaries on non AVX2 machines) and merged in master.  There are still some loosing ends, but should be eventually addressed in the future.

And I am definitely sure that there will be users that will find this very useful :)
