### ISSUE TITLE
[question] New release

### ISSUE THREAD

**Issue by xmnlab** [kiyo-masui/bitshuffle#94]
Hi everyone!

Is there any plan for a new release? it seems the last release was on Nov 5, 2018

**Comment by xmnlab** [comment]
hi everyone! it is me again :) just pinging here to see if there is any news about a new release.
thanks!

**Comment by Anthchirp** [comment]
Until this is addressed bitshuffle releases on conda-forge will stop with Python 3.9, as there is no newer version that we can build supporting Python 3.10 (cf. https://github.com/conda-forge/bitshuffle-feedstock/pull/22)

**Comment by Anthchirp** [comment]
@james-s-willis I see that you merged #98, but it looks like this new mechanism hasn't been used so far? The most recent pypi release is still from 4 years ago. Is there any particular reason why a new release couldn't be made?

**Comment by james-s-willis** [comment]
@Anthchirp I was waiting to get #104 merged in before creating a new release. I will ask @jrs65 again to perform one last review. I have since moved to a different job so this may take me some time.

**Comment by jrs65** [comment]
@Anthchirp @james-s-willis I've just cut a new release. Hopefully this should generate and upload binary wheels to PyPI correctly. I'll try and test those when they're there, and if they look like they're working I'll close the issue.

**Comment by Anthchirp** [comment]
I have an apparently working conda-build with the new version at https://github.com/conda-forge/bitshuffle-feedstock/pull/23.

I'll wait until you're happy with the release before hitting the big green button there.

Thank you!

**Comment by Anthchirp** [comment]
Just to let you know we have merged 0.4.1 onto conda-forge and it seems to work just fine.
